[versions]
kotlin-compiler = "1.8.10"
kotlin-coroutines = "1.8.1"

blocking-bridge = "3.0.0-180.1"

apache-commons-collection = "4.5.0-M2"
apache-commons-text = "1.12.0"

ktor = "2.3.10"

logging = "5.1.0"
slf4j = "2.0.17"
log4j = "2.23.1"

jackson = "2.17.1"
jackson-yaml = "2.19.0"

ktorm = "4.1.1"
hikari-cp = "5.1.0"

build-config = "4.0.4"  # 404 is good

maven-resolver-provider = "3.9.9"

[libraries]
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
blocking-bridge = { module = "me.him188:kotlin-jvm-blocking-bridge-runtime", version.ref = "blocking-bridge" }

apache-commons-collection = { module = "org.apache.commons:commons-collections4", version.ref = "apache-commons-collection" }
apache-commons-text = { module = "org.apache.commons:commons-text", version.ref = "apache-commons-text" }

kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "logging" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson-yaml" }

ktor-server-core-jvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-websockets-jvm = { module = "io.ktor:ktor-server-websockets-jvm", version.ref = "ktor" }
ktor-server-netty-jvm = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

ktorm-core = { module = "org.ktorm:ktorm-core", version.ref = "ktorm" }
ktorm-jackson = { module = "org.ktorm:ktorm-jackson", version.ref = "ktorm" }

hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari-cp" }

maven-resolver-provider = { module = "org.apache.maven.resolver:maven-resolver-provider", version.ref = "maven-resolver-provider" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version = "5.8.2" }
junit-bom = { module = "org.junit:junit-bom", version = "5.8.2" }

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-compiler" }
blocking-bridge = { id = "me.him188.kotlin-jvm-blocking-bridge", version.ref = "blocking-bridge" }
build-config = { id = "com.github.gmazzo.buildconfig", version.ref = "build-config" }